# Generated by Django 4.1.5 on 2023-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('type', models.CharField(choices=[('BRK', 'Завтрак'), ('LUN', 'Обед'), ('DIN', 'Ужин')], default='BRK', max_length=3, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0, help_text='Указывать рейтинг в integer')),
                ('cuisine', models.CharField(max_length=50)),
                ('work_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ресторан',
            },
        ),
    ]
