# Generated by Django 4.1.5 on 2023-01-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0, help_text='Указывать рейтинг в integer')),
                ('cuisine', models.CharField(max_length=50)),
                ('work_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='media', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('post_category', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('BRK', 'Завтрак'), ('LUN', 'Обед'), ('DIN', 'Ужин')], default='BRK', max_length=3, verbose_name='Тип')),
                ('title_of_restourant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='restourant_name', to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_categories', to='main.post')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_category', to='main.restaurant')),
                ('restourant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.restaurant')),
            ],
        ),
    ]
