# Generated by Django 4.1.5 on 2023-01-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_balanse',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
