# Generated by Django 4.1.5 on 2023-01-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_account_balanse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_balanse',
        ),
    ]
