# Generated by Django 4.1.5 on 2023-01-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_user_photo'),
        ('book', '0002_remove_user_username'),
    ]

    operations = [
    ]
